apiVersion: apps/v1
kind: Deployment
metadata:
  name: bits-smartlearn-students-deployment
spec:
  selector:
    matchLabels:
      app: bits-smartlearn-students
  replicas: 2
  template:
    metadata:
      labels:
        app: bits-smartlearn-students
    spec:
      containers:
        - name: bits-smartlearn-students
          image: bits-smartlearn-students
          ports:
            - containerPort: 3060
          imagePullPolicy: Never # Image should not be pulled
