apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlearn-students-deployment
spec:
  selector:
    matchLabels:
      app: smartlearn-students
  replicas: 2
  template:
    metadata:
      labels:
        app: smartlearn-students
    spec:
      containers:
        - name: smartlearn-students
          image: smart-learn-students-v1
          ports:
            - containerPort: 3000
          imagePullPolicy: Never # Image should not be pulled
