apiVersion: v1
kind: Service
metadata:
  name: bits-smartlearn-students-service
spec:
  selector:
    app: bits-smartlearn-students
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3060
      targetPort: 3060
      nodePort: 31520