apiVersion: v1
kind: Service
metadata:
  name: smartlearn-students-service
spec:
  selector:
    app: smartlearn-students
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31515